package TheThirteenth.exception.demo5;

import java.io.IOException;

public class ExceptionDemo05 {
    public static void main(String[] args) {
        //throw new IOException("自定义IO异常对象");
    }
}